import os
from dotenv import load_dotenv
load_dotenv()

BOOTSTRAP_SERVER = os.environ.get("BOOTSTRAP_SERVER")
KAFKA_PAYMENT_TOPIC = os.environ.get("KAFKA_PAYMENT_TOPIC")
KAFKA_ORDER_TOPIC = os.environ.get("KAFKA_ORDER_TOPIC")
KAFKA_NOTIFICATION_TOPIC = os.environ.get("KAFKA_NOTIFICATION_TOPIC")

KAFKA_PAYMENT_CONSUMER_GROUP_ID = os.environ.get("KAFKA_PAYMENT_CONSUMER_GROUP_ID")
KAFKA_ORDER_CONSUMER_GROUP_ID = os.environ.get("KAFKA_ORDER_CONSUMER_GROUP_ID")

KAFKA_PAYMENTS_DB_RESPONSE = os.environ.get("KAFKA_PAYMENTS_DB_RESPONSE")
KAFKA_ORDERS_DB_RESPONSE = os.environ.get("KAFKA_ORDERS_DB_RESPONSE")

AUTH_API_BASE_PATH = os.environ.get("AUTH_API_BASE_PATH")
DB_API_BASE_PATH = os.environ.get("DB_API_BASE_PATH")

STRIPE_APIKEY = os.environ.get("STRIPE_APIKEY")
API_LOGIN_ID = os.environ.get('API_LOGIN_ID')
TRANSACTION_KEY = os.environ.get('TRANSACTION_KEY')

client_session = None
